// Generated by https://quicktype.io

import { FileData } from "chonky/dist/types/file.types";
export interface FileMapData {
  rootFolderId: string;
  fileMap: FileMapGenerated;
}

export interface FileMapGenerated {
  [key: string]: FileData;
}

// export interface Folder {
//   id: string;
//   name: string;
//   isDir: boolean;
//   childrenIds: string[];
//   fullPath: string;
//   parentId?: string;
// }

// export interface File {
//   id: string;
//   name: string;
//   parentId: string;
//   size: number;
//   modDate: string;
//   fullPath: string;
// }
